# Arquivo: src/config/tasks.yaml
# Define as descrições e saídas esperadas para as tarefas dos agentes.
# A atribuição do agente e das ferramentas a cada tarefa será feita no código Python
# (ex: src/seu_projeto/tasks.py ou src/seu_projeto/crew.py).

# Tarefas para o Agente Triagem e Validação Documental
tarefa_validacao_documental:
  description: |
    Realize uma análise completa e rigorosa de todos os documentos fornecidos para o caso '{case_id}'.
    
    **DOCUMENTOS DISPONÍVEIS:**
    Os documentos do cliente já foram parseados e estão disponíveis na variável '{client_documents}'. 
    Cada documento contém:
    - name: Nome do arquivo
    - document_tag: Tag/tipo do documento
    - content: Conteúdo completo parseado com LlamaParse
    - url: URL original do documento
    
    **CHECKLIST DE VALIDAÇÃO:**
    Use o checklist normativo brasileiro fornecido em '{checklist_content}' como base para validação.
    O checklist detalha os critérios para:
    a) Documentos Cadastrais da PJ.
    b) Documentos Financeiros da PJ.
    c) Documentos dos Sócios / Representantes.

    **PROCESSO DE VALIDAÇÃO:**
    Para cada item do checklist:
    1. Identifique qual(is) documento(s) em '{client_documents}' corresponde(m) ao item
    2. Analise o conteúdo parseado do documento
    3. Verifique conformidade com os critérios (datas, assinaturas, completude, etc.)
    4. Considere regras de data em relação à '{current_date}'
    
    Se encontrar ambiguidades, consulte a 'Knowledge Base Query Tool' com queries específicas sobre políticas de validação.

  expected_output: |
    Um relatório estruturado em Markdown detalhando, para CADA item do checklist:
    1. **Nome do Item do Checklist**
    2. **Documento(s) Analisado(s)**: Nome e tag dos documentos de '{client_documents}' usados
    3. **Status**: Conforme/Não Conforme/Pendência/Não Aplicável
    4. **Análise Detalhada**: 
       - Conteúdo encontrado no documento
       - Critérios verificados
       - Motivo de não conformidade (se aplicável)
    5. **Observações**: Detalhes específicos, datas, assinaturas, etc.
    6. **Referência KB**: Se consultada a Knowledge Base
    
    O relatório deve cobrir TODOS os itens do checklist fornecido.

# Tarefas para o Agente Extrator de Informações
tarefa_extracao_dados:
  description: |
    Para o caso '{case_id}', extraia meticulosamente todas as informações relevantes dos documentos parseados fornecidos em '{client_documents}'.
    
    **DOCUMENTOS DISPONÍVEIS:**
    Cada documento em '{client_documents}' contém:
    - name: Nome do arquivo
    - document_tag: Tag/tipo do documento  
    - content: Conteúdo completo parseado
    - url: URL original
    
    **INFORMAÇÕES A EXTRAIR:**
    
    1. **Da Pessoa Jurídica (PJ):**
       - Razão Social Completa
       - Nome Fantasia (se houver)
       - CNPJ (formatado)
       - Data de Constituição/Abertura
       - Endereço Completo da Sede
       - Natureza Jurídica
       - Capital Social (Valor e Moeda)
       - Objeto Social (resumido)
       - Telefone e Email (se encontrados)
    
    2. **Dos Sócios/Acionistas e Representantes:**
       - Nome Completo
       - CPF (formatado)
       - RG (Número, Órgão, UF, Data)
       - Data de Nascimento
       - Nacionalidade, Estado Civil, Profissão
       - Endereço Residencial Completo
       - Participação Societária (%)
       - Cargo/Função na empresa
       - Data de Admissão/Eleição
    
    3. **Informações Financeiras:**
       - Faturamento dos últimos 12 meses
       - Nome do Contador responsável
       - Número de registro CRC
    
    4. **Outras Informações:**
       - Registro no órgão competente
       - Data da última alteração contratual
       - Informações adicionais relevantes

  expected_output: |
    Um objeto JSON estritamente estruturado com todas as informações extraídas:
    ```json
    {
      "dadosPessoaJuridica": {
        "razaoSocial": "...",
        "nomeFantasia": "...",
        "cnpj": "...",
        "dataConstituicao": "...",
        "endereco": {...},
        "naturezaJuridica": "...",
        "capitalSocial": "...",
        "objetoSocial": "...",
        "telefone": "...",
        "email": "..."
      },
      "dadosSociosRepresentantes": [
        {
          "nomeCompleto": "...",
          "cpf": "...",
          "rg": {...},
          "dataNascimento": "...",
          "endereco": {...},
          "participacaoSocietaria": "...",
          "cargo": "..."
        }
      ],
      "dadosFinanceiros": {
        "faturamento": "...",
        "contador": "...",
        "registroCRC": "..."
      },
      "outrasInformacoes": {...}
    }
    ```
    
    Se uma informação não for encontrada, use null. Não omita campos.

# Tarefas para o Agente Analista de Risco
tarefa_analise_risco_inconsistencias:
  description: |
    Conduza uma análise de risco aprofundada para o caso '{case_id}' baseando-se nos resultados das tarefas anteriores.
    
    **DADOS DISPONÍVEIS NO CONTEXTO:**
    - Relatório de validação documental (da tarefa anterior)
    - Dossiê cadastral completo (da tarefa anterior)
    - Documentos originais em '{client_documents}' (se necessário para esclarecimentos)
    
    **PROCESSO DE ANÁLISE:**
    
    1. **Análise de Pendências**: Revise o relatório de validação e identifique pendências críticas
    
    2. **Análise de Consistência**: Cruze todas as informações do dossiê cadastral:
       - Verifique consistência entre documentos
       - Identifique divergências de dados
       - Analise coerência temporal
    
    3. **Verificação Externa**: Use o CNPJ e CPFs extraídos para:
       - Verificar situação cadastral (Receita Federal)
       - Pesquisar reputação da empresa e sócios
       - Confirmar endereços e informações públicas
    
    4. **Consulta Knowledge Base**: Pesquise padrões de fraude, alertas de risco e casos similares
    
    5. **Parecer Final**: Elabore análise conclusiva com score de risco

  expected_output: |
    Um relatório consolidado em Markdown com as seguintes seções:
    
    # Relatório de Análise de Risco para o Caso '{case_id}'
    
    ## Sumário do Caso
    Breve resumo do caso e empresa analisada.
    
    ## Principais Pendências Documentais
    Lista das pendências críticas identificadas na validação.
    
    ## Relatório Detalhado de Inconsistências
    Para cada inconsistência:
    - Descrição da divergência
    - Documentos envolvidos
    - Comparação de informações conflitantes
    
    ## Resultados da Verificação Externa (Web)
    - Situação do CNPJ na Receita Federal
    - Reputação da empresa e sócios
    - Confirmação de endereços
    
    ## Insights da Knowledge Base
    Informações relevantes da base de conhecimento que influenciaram a análise.
    
    ## Parecer de Risco
    Análise conclusiva sobre o nível de risco percebido com justificativas.
    
    ## Score de Risco
    **Classificação**: Baixo/Médio/Alto
    
    **Justificativa**: Explicação detalhada da classificação atribuída.
